### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by natanshalva** [ptondereau/laravel-packme#19]
Run this: 
composer global require ptondereau/laravel-packme

Get this: 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ptondereau/laravel-packme ^2.1 -> satisfiable by ptondereau/laravel-packme[2.1.0].
    - Conclusion: remove symfony/filesystem v4.0.8
    - Conclusion: don't install symfony/filesystem v4.0.8
    - ptondereau/laravel-packme 2.1.0 requires symfony/filesystem ^3.1 -> satisfiable by 

Installation failed, reverting ./composer.json to its original content.

When i try to remove it: 

symfony/filesystem is not required in your composer.json and has not been removed
v4.0.8 is not required in your composer.json and has not been removed
Package "v4.0.8" listed for update is not installed. Ignoring.

**Comment by ptondereau** [comment]
thank you for reporting this issue.

I'll investigate later but PR are welcome!

**Comment by ghost** [comment]
Same issue.

**Comment by ptondereau** [comment]
@rxmg-nickk @natanshalva 
Drafted a new release should works now.

**Comment by ghost** [comment]
Awesome. Thanks. What turned out to be the issue?

**Comment by ghost** [comment]
OH I see.

https://github.com/ptondereau/laravel-packme/commit/04a6d81b46ce6ec3a38a252e5b4d013e292c9ee5#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R26

Sweet.
